#TERRAIN:
octaves=9
tex_w=1024
tex_h=1024
maxaltitude=4000
seed = 17
noise_scale=0.0025
#RIVERS:
river_count = 500
#CLIMATE:
wind_clamp = 996
wind_scale_downward = 2
river_evaporation = 0.5
sub_scale = 8
lat_top = 50
lat_bottom = 40